#!/usr/bin/ruby

require 'fileutils'
require 'pathname'
require 'tmpdir'


jar_entry = ARGV.shift
jars = ARGV.map {|jar| Pathname jar}

non_existant_jars = jars.reject { |jar| File.exist? jar }

unless non_existant_jars.empty?
  $stderr.puts "Non-existant jars: #{non_existant_jars}"
  exit(1)
end

jars.each do |jar|
  Dir.mktmpdir do |target|
    FileUtils.cp jar, target
    Dir.chdir(target) do
      %x(jar xf #{jar.basename} #{jar_entry})
      FileUtils.rm jar.basename
      matches = Dir['**/*'].select { |entry| File.file?(entry) };
      puts "#{jar}: No matches for #{jar_entry}" if matches.empty?
      matches.each do |entry|
        puts "#{jar}: #{entry}"
        IO.foreach(entry) { |line| puts "  #{line}" }
      end
    end
  end
end
