#!/usr/bin/ruby

require 'fileutils'
require 'pathname'

file = Pathname ARGV.shift
jars = ARGV

jars.collect {|jar| Pathname jar}.each do |jar|

  raise "#{jar} does not exist" unless File.exist? jar

  puts "#{jar} : #{file}"

  unless `jar tf #{jar} #{file}`.collect {|entry| entry.chomp}.first
    $stderr.puts "  #{jar} does not contain #{file}"
    next
  end

  target = "C:/tmp/catjar_#{jar.basename}"

  FileUtils.rm_rf target if File.exist? target
  FileUtils.mkdir target

  FileUtils.cp jar, target

  Dir.chdir(target) do
    system("jar xf * #{file}")
  end

  IO.foreach("#{target}/#{file}") do |line|
    puts "  #{line}"
  end

  FileUtils.rm_rf target if File.exist? target

end
