#!/bin/bash

IDENTITY=$1

if [ ! -e ~/.ssh/id_dsa.pub ] 
then
  ssh-keygen -t dsa -N ""
fi

cat ~/.ssh/id_dsa.pub | ssh $IDENTITY '[ ! -e ~/.ssh/id_dsa.pub ] && ssh-keygen -t dsa -N ""; cat - >>~/.ssh/authorized_keys'

