#!/usr/bin/ruby

if ARGV.length < 2
  puts 'Usage: search-jars <root-directory> <regular-expression>'
  exit 1
end

root_directory = ARGV[0]

jar_entry_pattern = Regexp.new ARGV[1]

file_glob = "#{root_directory}/**/*.[ejw]ar"

Dir.glob(file_glob) do |jar_file|
  next if File.directory?(jar_file)
  jar_contents = `jar -tf #{jar_file}`
  jar_entries = jar_contents.split("\n")
  jar_entries.each do |jarEntry|
    if jar_entry_pattern.match(jarEntry)
      $stdout.puts "#{jar_file}: #{jarEntry}"
    end
  end
end

exit 0
